import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { KERNEL_CAPABILITY_CONTRACTS } from "../kernel/capabilities/contracts.js";
import { GENERATED_KERNEL_CONTRACT_TESTS } from "../kernel/capabilities/generated-contract-test-evidence.js";
import type { KernelContractTestEvidence } from "../kernel/capabilities/types.js";
import {
  KERNEL_CAPABILITY_CONTRACT_CASES,
  runKernelCapabilityContractCases,
} from "./kernel-capability-contract-cases.js";

const GENERATED_EVIDENCE_SOURCE_PATH = join(
  process.cwd(),
  "src/kernel/capabilities/generated-contract-test-evidence.ts",
);

async function main() {
  assertContractCaseCoverage();
  const checkedAtByTestId = new Map(GENERATED_KERNEL_CONTRACT_TESTS.map((item) => [item.testId, item.checkedAt]));
  const evidence = await runKernelCapabilityContractCases({ checkedAtByTestId });
  assertEvidenceMatchesContracts(evidence);
  const rendered = renderGeneratedContractTestEvidence(evidence);

  if (process.argv.includes("--write")) {
    writeFileSync(GENERATED_EVIDENCE_SOURCE_PATH, rendered);
    console.log("✓ regenerated simulated kernel capability contract evidence");
    return;
  }

  const current = readFileSync(GENERATED_EVIDENCE_SOURCE_PATH, "utf8");
  assert.equal(
    current,
    rendered,
    "Generated simulated kernel capability contract evidence is stale. Run `npm run build:server && node dist/tests/kernel-capability-contract-evidence-harness.js --write`, then rebuild.",
  );

  console.log("✓ generated simulated kernel capability evidence matches local projector contract cases");
}

function assertContractCaseCoverage() {
  const seen = new Set<string>();
  for (const testCase of KERNEL_CAPABILITY_CONTRACT_CASES) {
    assert.equal(seen.has(testCase.testId), false, `Duplicate kernel capability contract test id: ${testCase.testId}`);
    seen.add(testCase.testId);
    const mapping = KERNEL_CAPABILITY_CONTRACTS.find((contract) => contract.kernel === testCase.kernel)?.mappings.find(
      (item) => item.capability === testCase.capability && item.expectedContractTest === testCase.testId,
    );
    assert.ok(mapping, `${testCase.testId} must correspond to a declared kernel capability mapping`);
  }
}

function assertEvidenceMatchesContracts(evidence: KernelContractTestEvidence[]) {
  const caseIds = new Set(KERNEL_CAPABILITY_CONTRACT_CASES.map((testCase) => testCase.testId));
  for (const item of evidence) {
    assert.equal(item.passed, true, `${item.testId} evidence can only be written after the test passes`);
    assert.equal(
      caseIds.has(item.testId),
      true,
      `${item.testId} evidence must be produced by a registered contract case`,
    );
    const mapping = KERNEL_CAPABILITY_CONTRACTS.find((contract) => contract.kernel === item.kernel)?.mappings.find(
      (entry) => entry.capability === item.capability && entry.expectedContractTest === item.testId,
    );
    assert.ok(mapping, `${item.testId} must correspond to a declared kernel capability mapping`);
  }
}

function renderGeneratedContractTestEvidence(evidence: KernelContractTestEvidence[]): string {
  const entries = evidence
    .map(
      (item) => `  {
${Object.entries(item)
  .map(([key, value]) => `    ${key}: ${JSON.stringify(value)},`)
  .join("\n")}
  },`,
    )
    .join("\n");
  return `// Generated by src/tests/kernel-capability-contract-evidence-harness.ts.
// Simulated evidence only; do not use this file as certified exposed capability proof.
// Do not edit by hand. Run \`node dist/tests/kernel-capability-contract-evidence-harness.js --write\`.
import type { KernelContractTestEvidence } from "./types.js";

export const GENERATED_KERNEL_CONTRACT_TESTS: KernelContractTestEvidence[] = [
${entries}
];
`;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
