export const STANDARD_KERNEL_CAPABILITY_IDS = [
  "message.streamText",
  "turn.lifecycle",
  "session.lifecycle",
  "planning.plan",
  "interaction.askUser",
  "tools.hostTool",
  "tools.nativeTool",
  "tools.mcpServers",
  "tools.parallelCalls",
  "tool.progress",
  "approval.request",
  "control.stop",
  "control.steer",
  "session.compact",
  "session.goal",
  "auth.refresh",
  "sandbox.policy",
  "budget.limit",
  "diagnostics.usage",
  "response.speed",
  "media.input",
  "output.structured",
  "output.artifacts",
  "reasoning.nativeText",
  "reasoning.summary",
  "knowledge.skills",
] as const;

export type KernelCapabilityId = (typeof STANDARD_KERNEL_CAPABILITY_IDS)[number];

