import { z } from "zod/v4";

export const flowStatusSchema = z.enum(["pending", "running", "waiting_user", "done", "failed"]);
export const flowStepStatusSchema = z.enum(["pending", "running", "waiting", "done", "failed"]);

export const flowStepSchema = z
  .object({
    id: z.string().min(1),
    title: z.string().min(1),
    owner: z.string().min(1),
    status: flowStepStatusSchema,
    output: z.string().min(1).optional(),
    blocking: z.boolean().optional(),
    note: z.string().optional(),
  })
  .passthrough();

export const flowFrontmatterSchema = z
  .object({
    flow: z.literal("v1"),
    title: z.string().min(1),
    status: flowStatusSchema,
    initiator: z.string().min(1).optional(),
    started: z.string().min(1).optional(),
    updated: z.string().min(1).optional(),
    steps: z.array(flowStepSchema).min(1),
  })
  .passthrough();

export type FlowFrontmatter = z.infer<typeof flowFrontmatterSchema>;
export type FlowStep = z.infer<typeof flowStepSchema>;

export interface FlowMarkdownParseResult {
  body: string;
  frontmatter?: FlowFrontmatter;
  issues: string[];
  rawFrontmatter?: Record<string, unknown>;
  valid: boolean;
}

export function isFlowMarkdownPath(path: string): boolean {
  return /\.flow\.md$/i.test(path);
}

export function parseFlowMarkdown(text: string): FlowMarkdownParseResult {
  const normalized = text.replace(/\r\n/g, "\n");
  if (!normalized.startsWith("---\n")) {
    return {
      body: normalized,
      issues: ["flow frontmatter missing"],
      valid: false,
    };
  }

  const end = normalized.indexOf("\n---\n", 4);
  if (end < 0) {
    return {
      body: normalized,
      issues: ["flow frontmatter is not closed"],
      valid: false,
    };
  }

  const rawFrontmatter = parseFlowFrontmatterYaml(normalized.slice(4, end));
  const result = flowFrontmatterSchema.safeParse(rawFrontmatter);
  if (!result.success) {
    return {
      body: normalized.slice(end + 5).trimStart(),
      issues: result.error.issues.map((issue) => `${issue.path.join(".") || "flow"}: ${issue.message}`),
      rawFrontmatter,
      valid: false,
    };
  }

  return {
    body: normalized.slice(end + 5).trimStart(),
    frontmatter: result.data,
    issues: [],
    rawFrontmatter,
    valid: true,
  };
}

export function serializeFlowMarkdown(frontmatter: FlowFrontmatter, body?: string): string {
  const kind = stringFlowFrontmatterField(frontmatter, "kind");
  const lines = [
    "---",
    "flow: v1",
    ...(kind ? [`kind: ${yamlScalar(kind)}`] : []),
    `title: ${yamlScalar(frontmatter.title)}`,
    `status: ${frontmatter.status}`,
    ...(frontmatter.initiator ? [`initiator: ${yamlScalar(frontmatter.initiator)}`] : []),
    ...(frontmatter.started ? [`started: ${yamlScalar(frontmatter.started)}`] : []),
    ...(frontmatter.updated ? [`updated: ${yamlScalar(frontmatter.updated)}`] : []),
    "steps:",
  ];
  for (const step of frontmatter.steps) {
    lines.push(
      `  - id: ${yamlScalar(step.id)}`,
      `    title: ${yamlScalar(step.title)}`,
      `    owner: ${yamlScalar(step.owner)}`,
      `    status: ${step.status}`,
    );
    const activityRunId = stringFlowStepField(step, "activityRunId");
    const messageId = stringFlowStepField(step, "messageId");
    const roomId = stringFlowStepField(step, "roomId");
    if (activityRunId) lines.push(`    activityRunId: ${yamlScalar(activityRunId)}`);
    if (messageId) lines.push(`    messageId: ${yamlScalar(messageId)}`);
    if (roomId) lines.push(`    roomId: ${yamlScalar(roomId)}`);
    if (step.blocking !== undefined) lines.push(`    blocking: ${step.blocking ? "true" : "false"}`);
    if (step.output) lines.push(`    output: ${yamlScalar(step.output)}`);
    if (step.note !== undefined) lines.push(`    note: ${yamlScalar(step.note)}`);
  }
  const defaultBody = `# ${frontmatter.title}\n\nGenerated by routine runner.\n`;
  const markdownBody = normalizeFlowMarkdownBody(body ?? defaultBody);
  return `${lines.join("\n")}\n---\n\n${markdownBody}`;
}

function parseFlowFrontmatterYaml(text: string): Record<string, unknown> {
  const output: Record<string, unknown> = {};
  const steps: Record<string, unknown>[] = [];
  let inSteps = false;
  let currentStep: Record<string, unknown> | undefined;

  for (const line of text.split("\n")) {
    if (!line.trim() || /^\s*#/.test(line)) continue;

    if (inSteps) {
      const stepStart = line.match(/^\s{2}-\s+([A-Za-z0-9_-]+):\s*(.*)$/);
      if (stepStart) {
        currentStep = {};
        currentStep[stepStart[1] || ""] = parseYamlScalar(stepStart[2] || "");
        steps.push(currentStep);
        continue;
      }

      const stepProperty = line.match(/^\s{4}([A-Za-z0-9_-]+):\s*(.*)$/);
      if (stepProperty && currentStep) {
        currentStep[stepProperty[1] || ""] = parseYamlScalar(stepProperty[2] || "");
        continue;
      }
    }

    const topLevel = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!topLevel) continue;
    const key = topLevel[1] || "";
    const rawValue = topLevel[2] || "";
    if (key === "steps") {
      inSteps = true;
      output.steps = steps;
      continue;
    }
    inSteps = false;
    output[key] = parseYamlScalar(rawValue);
  }

  if (steps.length && !Array.isArray(output.steps)) {
    output.steps = steps;
  }
  return output;
}

function parseYamlScalar(value: string): unknown {
  const trimmed = value.trim();
  if (!trimmed) return "";
  if (trimmed === "true") return true;
  if (trimmed === "false") return false;
  if (trimmed === "[]") return [];
  if ((trimmed.startsWith('"') && trimmed.endsWith('"')) || (trimmed.startsWith("'") && trimmed.endsWith("'"))) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

function yamlScalar(value: string): string {
  const normalized = value.replace(/\s+/g, " ").trim();
  return /^[A-Za-z0-9._/@:-]+$/.test(normalized) ? normalized : JSON.stringify(normalized);
}

function stringFlowStepField(step: FlowStep, key: string): string {
  const value = step[key];
  return typeof value === "string" ? value.trim() : "";
}

function stringFlowFrontmatterField(frontmatter: FlowFrontmatter, key: string): string {
  const value = frontmatter[key];
  return typeof value === "string" ? value.trim() : "";
}

function normalizeFlowMarkdownBody(body: string): string {
  const normalized = body.trimStart();
  return normalized.endsWith("\n") ? normalized : `${normalized}\n`;
}
